// Real IITGN rooms extracted from VOIP Directory (41 pages, ~500 entries)
// Format: AB{building}/{room} with suffix letters for subdivided offices

export const iitgnRooms = [
  // === DEAN & SENIOR ADMIN OFFICES (AB3 Core Building) ===
  { building: 'AB3', roomNumber: '313', label: 'AB3/313 — Dean, Campus Development', purpose: 'Dean Office', capacity: 6 },
  { building: 'AB3', roomNumber: '301', label: 'AB3/301 — Director (Prof. Rajat Moona)', purpose: 'Director Office', capacity: 8 },
  { building: 'AB3', roomNumber: '329', label: 'AB3/329 — Faculty Affairs Office', purpose: 'Admin Office', capacity: 12 },
  { building: 'AB3', roomNumber: '328A', label: 'AB3/328A — Dean, General Administration', purpose: 'Dean Office', capacity: 6 },
  { building: 'AB3', roomNumber: '327A', label: 'AB3/327A — Prof-In-Charge, External Relations', purpose: 'Admin Office', capacity: 6 },
  { building: 'AB3', roomNumber: '306E', label: 'AB3/306E — Prof. Sushobhan Sen (Civil Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB3', roomNumber: '322A', label: 'AB3/322A — Research Park Advisor', purpose: 'Admin Office', capacity: 4 },
  { building: 'AB3', roomNumber: '324A', label: 'AB3/324A — IIEC Office', purpose: 'Admin Office', capacity: 8 },
  { building: 'AB3', roomNumber: '326A', label: 'AB3/326A — R&D Office', purpose: 'Admin Office', capacity: 10 },
  { building: 'AB3', roomNumber: '318', label: 'AB3/318 — Deputy Manager, Research Park', purpose: 'Admin Office', capacity: 4 },
  { building: 'AB3', roomNumber: '311', label: 'AB3/311 — Campus Development (Ashish Kanojiya)', purpose: 'Admin Office', capacity: 4 },
  { building: 'AB3', roomNumber: '308', label: 'AB3/308 — General Administration', purpose: 'Admin Office', capacity: 10 },
  { building: 'AB3', roomNumber: '302B', label: 'AB3/302B — Director Office (Gaurav Shukla)', purpose: 'Admin Office', capacity: 4 },
  { building: 'AB3', roomNumber: '328B', label: 'AB3/328B — Prof-In-Charge, Faculty Affairs', purpose: 'Admin Office', capacity: 4 },

  // === ACADEMIC OFFICES (AB3) ===
  { building: 'AB3', roomNumber: '101', label: 'AB3/101 — Academics Office', purpose: 'Admin Office', capacity: 15 },
  { building: 'AB3', roomNumber: '102', label: 'AB3/102 — Student Affairs Office', purpose: 'Admin Office', capacity: 12 },
  { building: 'AB3', roomNumber: '103D', label: 'AB3/103D — Registrar Office', purpose: 'Admin Office', capacity: 10 },
  { building: 'AB3', roomNumber: '107', label: 'AB3/107 — Library Office', purpose: 'Admin Office', capacity: 8 },
  { building: 'AB3', roomNumber: '108', label: 'AB3/108 — Advisor (Library & Archives)', purpose: 'Admin Office', capacity: 4 },
  { building: 'AB3', roomNumber: '111', label: 'AB3/111 — Finance & Accounts', purpose: 'Admin Office', capacity: 15 },
  { building: 'AB3', roomNumber: '112', label: 'AB3/112 — Career Development Services (CDS)', purpose: 'Admin Office', capacity: 12 },
  { building: 'AB3', roomNumber: '112C', label: 'AB3/112C — Student Placement Office', purpose: 'Admin Office', capacity: 10 },
  { building: 'AB3', roomNumber: '201', label: 'AB3/201 — Material Management', purpose: 'Admin Office', capacity: 8 },

  // === AB5 / AB6 — DEAN OFFICES & FACULTY ===
  { building: 'AB6', roomNumber: '335', label: 'AB6/335 — Dean, Academic Affairs (PG)', purpose: 'Dean Office', capacity: 6 },
  { building: 'AB6', roomNumber: '356', label: 'AB6/356 — Associate Dean, Academic Affairs (UG)', purpose: 'Dean Office', capacity: 6 },
  { building: 'AB6', roomNumber: '335A', label: 'AB6/335A — Prof. Saumyakanti Khatua (Chemistry)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '340', label: 'AB6/340 — Prof. Atul Dixit (Mathematics)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '347', label: 'AB6/347 — Prof. Arnab Saha (Mathematics)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '344', label: 'AB6/344 — Prof. Sanjaykumar Amrutia (Math)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '337', label: 'AB6/337 — Prof. Biswajit Mondal (Chemistry)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '341', label: 'AB6/341 — Prof. Sudhansu Sharma (Chemistry)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '314A', label: 'AB6/314A — Prof. Gopinadhan Kalon (Physics)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '315B', label: 'AB6/315B — Prof. Prasanna Venkatesh (Physics)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '326', label: 'AB6/326 — Prof. Anand Sengupta (Physics)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '329', label: 'AB6/329 — Prof. Sudipta Sarkar (Physics)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '330', label: 'AB6/330 — Prof. Vinod Chandra (Physics)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '352', label: 'AB6/352 — Prof. V.N. Prabhakar (HSS)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '334', label: 'AB6/334 — Prof. Udit Bhatia (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '331', label: 'AB6/331 — Prof. Pranab Mohapatra (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '406', label: 'AB6/406 — Prof. Amit Prashant (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '405', label: 'AB6/405 — Prof. Gaurav Srivastava (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '403', label: 'AB6/403 — Prof. Sameer Patel (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB6', roomNumber: '319', label: 'AB6/319 — Alumni Relations Office', purpose: 'Admin Office', capacity: 15 },
  { building: 'AB6', roomNumber: '306', label: 'AB6/306 — Estate & Works (Security Advisor)', purpose: 'Admin Office', capacity: 6 },
  { building: 'AB6', roomNumber: '407B', label: 'AB6/407B — Coordinator, IMS', purpose: 'Admin Office', capacity: 4 },

  // === AB5 — FACULTY OFFICES ===
  { building: 'AB5', roomNumber: '348', label: 'AB5/348 — Prof. Bhaskar Datta (Chemistry)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '334', label: 'AB5/334 — Prof. Dhiman Basu (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '307', label: 'AB5/307 — Prof. Chhavi Pandey (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '336B', label: 'AB5/336B — Prof. Vikrant Jain (Earth Sciences)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '337', label: 'AB5/337 — Prof. Sudhir K. Arora (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '308', label: 'AB5/308 — Prof. Abinaya Sampath (Chem Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '322', label: 'AB5/322 — Prof. Prachi Thareja (Chem Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '403', label: 'AB5/403 — Prof. Sameer Dalvi (Chem Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '317A', label: 'AB5/317A — Prof. Ashutosh Srivastava (Bio Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '316A', label: 'AB5/316A — Prof. Pratik Mutha (Bio Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '406', label: 'AB5/406 — Prof. Harish P.M. (Mechanical)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '338', label: 'AB5/338 — Prof. Deepak Singhania (HSS)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '349', label: 'AB5/349 — Prof. Dhiraj Bhatia (Bio Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '341', label: 'AB5/341 — Prof. Chetan Pahlajani (Math)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB5', roomNumber: '352', label: 'AB5/352 — Prof. Rusa Mandal (Physics)', purpose: 'Faculty Office', capacity: 3 },

  // === AB4 — FACULTY (HSS, CHEMISTRY, MECHANICAL) ===
  { building: 'AB4', roomNumber: '405', label: 'AB4/405 — Prof. Chinmay Ghoroi (Chem Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '404', label: 'AB4/404 — Prof. Sriram Gundimeda (Chemistry)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '403', label: 'AB4/403 — Prof. Sudipta Basu (Chemistry)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '324', label: 'AB4/324 — Prof. Sairam Mallajosyula (Chemistry)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '335A', label: 'AB4/335A — Prof. Ajanta Sachan (Civil)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '333A', label: 'AB4/333A — Prof. Arka Chattopadhyay (HSS)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '333B', label: 'AB4/333B — Prof. Nishaant Choksi (HSS)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '334B', label: 'AB4/334B — Prof. Arnapurna Rath (HSS)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '327', label: 'AB4/327 — Prof. Ambika Aiyadurai (HSS)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '332A', label: 'AB4/332A — Shashi Tiwari (Counselor)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '308', label: 'AB4/308 — Prof. Atul Bhargav (Mechanical)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '309', label: 'AB4/309 — Prof. Ravi Sastri Ayyagari (Mech)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '320', label: 'AB4/320 — Prof. Uddipta Ghosh (Mechanical)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '321', label: 'AB4/321 — Prof. Soumyadip Sett (Mech)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '312', label: 'AB4/312 — Prof. Dilip Sundaram (Mech)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '313', label: 'AB4/313 — Prof. Vineet Vashista (Mech)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '314A', label: 'AB4/314A — Prof. Sharad Gupta (Bio Engg)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB4', roomNumber: '315', label: 'AB4/315 — Dilip Kashyap (External Relations)', purpose: 'Admin Office', capacity: 4 },
  { building: 'AB4', roomNumber: '108A', label: 'AB4/108A — Prof. Alok Kanungo (HSS)', purpose: 'Faculty Office', capacity: 3 },

  // === AB11, AB12, AB13 — MATERIALS, EARTH SCI, CSE ===
  { building: 'AB11', roomNumber: '306A', label: 'AB11/306A — Prof. Emila Panda (Materials)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB11', roomNumber: '308B', label: 'AB11/308B — Prof. Amit Arora (Materials)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB11', roomNumber: '309D', label: 'AB11/309D — Prof. Abhijit Mishra (Materials)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB11', roomNumber: '309B', label: 'AB11/309B — Prof. Sriharitha Rowthu (Materials)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB11', roomNumber: '305A', label: 'AB11/305A — Prof. Pradipta Ghosh (Materials)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB11', roomNumber: '308A', label: 'AB11/308A — Prof. Raghavan Ranganathan (Materials)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB11', roomNumber: '306B', label: 'AB11/306B — Prof. Superb Misra (Materials)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB12', roomNumber: '402B', label: 'AB12/402B — Prof. Achyut Mishra (Earth Sci)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB12', roomNumber: '406C', label: 'AB12/406C — Prof. Sonal Khanolkar (Earth Sci)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB12', roomNumber: '406A', label: 'AB12/406A — Prof. Pankaj Khanna (Earth Sci)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '405G', label: 'AB13/405G — Prof. Anirban Dasgupta (CSE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '405H', label: 'AB13/405H — Prof. Neeldhara Misra (CSE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '405A', label: 'AB13/405A — Prof. Abhishek Bichhawat (CSE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '405B', label: 'AB13/405B — Prof. Balagopal Komarath (CSE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '405E', label: 'AB13/405E — Prof. Sameer Kulkarni (CSE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '405F', label: 'AB13/405F — Prof. Bireswar Das (CSE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '401C', label: 'AB13/401C — Prof. Nipun Batra (CSE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '402A', label: 'AB13/402A — Prof. Shouvick Mondal (CSE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '323A', label: 'AB13/323A — Prof. Anand Kumar (EE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '321C', label: 'AB13/321C — Prof. Arup Chakraborty (EE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '322A', label: 'AB13/322A — Prof. Nithin George (EE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '322B', label: 'AB13/322B — Prof. Shanmuganathan Raman (EE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '322D', label: 'AB13/322D — Prof. Uttama Lahiri (EE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '326B', label: 'AB13/326B — Prof. Ragavan K (EE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '326D', label: 'AB13/326D — Prof. Pallavi Bharadwaj (EE)', purpose: 'Faculty Office', capacity: 3 },
  { building: 'AB13', roomNumber: '327A', label: 'AB13/327A — Prof. Nihar Mohapatra (EE)', purpose: 'Faculty Office', capacity: 3 },

  // === MEETING ROOMS & BOARD ROOMS ===
  { building: 'AB3', roomNumber: 'CB-Board', label: 'AB3 Board Room — Main', purpose: 'Board Room', capacity: 20 },
  { building: 'AB3', roomNumber: 'CB-Meeting', label: 'AB3 Committee Room', purpose: 'Meeting Room', capacity: 12 },
  { building: 'AB6', roomNumber: 'CB-Dean', label: 'AB6 Dean Conference Room', purpose: 'Meeting Room', capacity: 15 },
  { building: 'Guest House', roomNumber: 'GH-C201', label: 'Guest House Board Room (1st Floor)', purpose: 'Board Room', capacity: 16 },
  { building: 'Guest House', roomNumber: 'GH-C301', label: 'Guest House Meeting Room (2nd Floor)', purpose: 'Meeting Room', capacity: 10 },
  { building: 'Guest House', roomNumber: 'GH-C101', label: 'Guest House Conference Hall (Ground)', purpose: 'Conference Hall', capacity: 40 },

  // === LECTURE HALLS ===
  { building: 'HB', roomNumber: '28/103', label: 'HB Classroom 28/103', purpose: 'Classroom', capacity: 60 },
  { building: 'HB', roomNumber: '9/301', label: 'HB Classroom 9/301', purpose: 'Classroom', capacity: 60 },

  // === LIBRARY ===
  { building: 'AB3', roomNumber: 'LIB-Sem', label: 'Library Seminar Hall', purpose: 'Seminar Hall', capacity: 100 },
  { building: 'AB3', roomNumber: 'LIB-Disc', label: 'Library Discussion Room', purpose: 'Meeting Room', capacity: 8 },

  // === GUEST HOUSE ROOMS ===
  { building: 'Guest House', roomNumber: 'GH-Dining1', label: 'Guest House Dining (1st Floor)', purpose: 'Dining', capacity: 30 },
  { building: 'Guest House', roomNumber: 'GH-Dining2', label: 'Guest House Dining (2nd Floor)', purpose: 'Dining', capacity: 30 },
  { building: 'Guest House', roomNumber: 'GH-Lounge', label: 'Guest House Lounge', purpose: 'Lounge', capacity: 20 },

  // === CENTRAL ARCADE & COMMON ===
  { building: 'Central Arcade', roomNumber: 'CA-Art', label: 'Art Studio', purpose: 'Studio', capacity: 15 },
  { building: 'AB5', roomNumber: '101', label: 'AB5/101 — Gymnasium', purpose: 'Sports Facility', capacity: 50 },
  { building: 'Sports Complex', roomNumber: 'SC-Main', label: 'Sports Complex Main Hall', purpose: 'Sports Facility', capacity: 200 },
]
